[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# also replaces music for custom packs
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "(G.STATE == G.STATES.SPLASH and '') or"
position = "after"
payload = '''((G.pack_cards and G.pack_cards.cards and G.pack_cards.cards[1] and G.pack_cards.cards[1].ability.set == 'Code') or (G.GAME and G.GAME.USING_CODE) and 'musicProg') or'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "(G.shop and not G.shop.REMOVED and 'music4') or"
position = "before"
payload = '''
((to_big(G.GAME.round_scores['hand'].amt) > to_big(10)^1000000) and 'musicBig') or
(cry_has_exotic() and 'musicExotic') or
'''
match_indent = true