[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Checkered Deck Effect
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if self.GAME.starting_params.no_faces and (_r == 'K' or _r == 'Q' or _r == 'J') then keep = false end"
position = "after"
payload = '''
if self.GAME.selected_back.effect.config.cry_antimatter then
    if _s == 'C' then _s = 'S' end
    if _s == 'D' then _s = 'H' end
end
'''
match_indent = true

# Anaglyph Deck Effect
[[patches]]
[patches.pattern]
target = "back.lua"
pattern = "if self.name == 'Anaglyph Deck' and args.context == 'eval' and G.GAME.last_blind and G.GAME.last_blind.boss then"
position = "at"
payload = "if (self.name == 'Anaglyph Deck' or self.name == 'cry-Antimatter') and args.context == 'eval' and G.GAME.last_blind and G.GAME.last_blind.boss then"
match_indent = true